@add = http://localhost:5000/api/password-manager/add


POST {{add}}
Content-Type: application/json

{
    "service": "google",
    "user_id": 2,
    "password": "test1234"
}

###

@see = http://localhost:5000/api/password-manager/see

POST {{see}}
Content-Type: application/json

{
    "service": "google",
    "user_id": 2,
    "password": "test1234"
}

###

@del = http://localhost:5000/api/password-manager/delete

DELETE {{del}}
Content-Type: application/json

{
    "service": "google",
    "user_id": 2
}

###

@exists = http://localhost:5000/api/password-manager/exists

GET {{exists}}?user_id=2&service=google
